### ISSUE TITLE
[Discussion]

### ISSUE THREAD

**Issue by electr0sheep** [lsellens/octoprint-manual_bed_tramming#13]
Hey guys, I don't really know what I'm doing with gcode, but it seems like the current feed rate could be much faster. I've been experimenting with G0 X Y F40000 and the printer hauls butt. Aside from possibly being a safety hazard, is there a reason why I shouldn't set the feed rate a lot faster than 5000?

Should I just make the feed rate customizable as well? If so what are some good defaults?

**Comment by b-morgan** [comment]
electr0sheep, Are you subscribed to the google group OctoPrint? If not, you should be as that may be a better place to ask this question. Also people in that group are asking questions about your plugin. It seems quite popular, congratulations!
