### ISSUE TITLE
Suggestion: Option to set a custom Z

### ISSUE THREAD

**Issue by Havenwar** [lsellens/octoprint-manual_bed_tramming#16]
Not everyone levels their bed with z at zero, so having the option to set a custom z height in addition to the existing options for x and y would be awesome so people have more options to do things their way.

**Comment by electr0sheep** [comment]
That's interesting. I couldn't even begin to fathom why people wouldn't level the bed with z set to 0, but it won't be that hard to add, so I can work on adding that as an option.

**Comment by electr0sheep** [comment]
@Havenwar I have implemented both of your suggestions (this one plus rearranging the buttons), but I'm in the middle of a print so I can't test my Z axis changes right now. I will test and push a new version of the plugin tomorrow.

**Comment by Havenwar** [comment]
Thanks! As for why the general idea I believe is that it's easier to feel the drag on say a 4mm drill bit than a 0.02mm feeler gauge, which makes it easier to get a very accurate and repeatable level. This also lets you level with a z0 of "true 0" instead of "0+thickness of a piece of paper" since you set the z to measure at to the exact thickness of the implement used to measure with. 

I am still experimenting with it so I couldn't say if it's better or not, but it's always nice to have options.

**Comment by electr0sheep** [comment]
Just pushed 2.0.1 which contains the new settings
