### ISSUE TITLE
CR-10S does not respond to move after "Apply heat"

### ISSUE THREAD

**Issue by photojohn** [lsellens/octoprint-manual_bed_tramming#19]
When pressed "Apply heat" CR-10S does not respond to any movement requests - not from OctoPrint, not from printer menu (tried HOME option). Helps, when restart printer. Was repeatable multiple times, works with OctoPrint original heat control. At least bed started to heat.
No settings were touched, started to use straight away.

**Comment by electr0sheep** [comment]
This is due to gcode I use to apply the heat. I will make this an option, since I've had other complaints about it as well.

**Comment by electr0sheep** [comment]
This issue should be resolved with the latest release: https://github.com/electr0sheep/OctoPrint-Cr10_leveling/releases/tag/v2.1.0
