### ISSUE TITLE
But how to get it to work?

### ISSUE THREAD

**Issue by bcsteeve** [lsellens/octoprint-manual_bed_tramming#2]
Installation said success... nothing there though.  I don't see what your screenshot shows.  Just normal "controls" page.  Plugin manager shows it as enabled.

??

**Comment by bcsteeve** [comment]
reboot.  of course.  sorry

**Comment by electr0sheep** [comment]
But still, the installation process is not clear. I need to update this to make this more smooth.

**Comment by electr0sheep** [comment]
Installation process is much more smooth as of v1.1.0
