### ISSUE TITLE
Z doesn't change anymore

### ISSUE THREAD

**Issue by johnnygizmo** [lsellens/octoprint-manual_bed_tramming#21]
Since a recent update, the z doesn't change between button presses. Lower z is set to 0 and upper is set to 15. (Version 2.1.0)

Standard Z movement buttons still work fine.

**Comment by johnnygizmo** [comment]
More info: On clicking a corner button, these are the only commands sent to the printer

Send: G90
Recv: ok
Send: G0 X270Y270F3600
Recv: ok

**Comment by electr0sheep** [comment]
@johnnygizmo I just tested this with my CR-10, and the z was changing. For example, when I clicked `Bottom Left`, the z went up by 10 units, moved into the bottom left position, and the z went down by 10 units.

Can you confirm that I am understanding correctly, and if I am, what 3D printer are you using?

Can anyone else reproduce this issue?

**Comment by johnnygizmo** [comment]
I reinstalled my Octopi (for other reasons) and the plugin works fine now. Sorry for the confusion.
