### ISSUE TITLE
Python 3 Compatibility

### ISSUE THREAD

**Issue by cp2004** [lsellens/octoprint-manual_bed_tramming#27]
Hi there! I don't use this plugin (Don't have a CR10, but **at least 1,300 users have installed this plugin - It's popular!**) but I am helping out plugins getting to Python 3 compatibility. 
As you are probably aware, OctoPrint currently supports Python 2 & 3 simultaneously. Users will begin migrating to Python 3 soon and your plugin will not be installable. As of March 2021, it will switch to Python 3 only.
Please see the guide [here](https://docs.octoprint.org/en/master/plugins/python3_migration.html)

Having taken a look at your plugin, there is not too much Python so if you don't want to update it, I could PR to sort it out. It could just need the compatibility flag detailed in the link above.

**Comment by lsellens** [comment]
I've tested and this addon is python 3 compatible. It just needs the flag added.

**Comment by ScruffR** [comment]
> I've tested and this addon is python 3 compatible. It just needs the flag added.

How did you install it? 
I've tried on my OctoPi but the plugin will never get enabled.

**Comment by cp2004** [comment]
You will need to add the Python compatibility flag yourself, or force it compatible as a development option. I'll create a PR you can use to install it.

**Comment by lsellens** [comment]
@ScruffR as cp2004 said you can edit the addon to include the missing tag or config octoprint to to force its use as described here
https://docs.octoprint.org/en/master/plugins/python3_migration.html#telling-octoprint-your-plugin-is-python-3-ready

**Comment by ScruffR** [comment]
Yup, I tried @cp2004's version and it worked :+1:
