### ISSUE TITLE
[Feature Request] Python 3 Compatibility

### ISSUE THREAD

**Issue by IKnowNow** [lsellens/octoprint-manual_bed_tramming#28]
Please add Python 3 Compatibility as outlined [here](https://docs.octoprint.org/en/master/plugins/python3_migration.html).

**Comment by lsellens** [comment]
I've tested and this addon is python 3 compatible. It just needs the flag added.

**Comment by happy1234567** [comment]
This plugin stopped working. Is this why?  The python versions?
![image](https://user-images.githubusercontent.com/36652924/98845714-1bdbb580-241c-11eb-88b1-46c837e935e2.png)

**Comment by fatboy1271** [comment]
Is there any way for someone to get this working? It's the best bed leveling plug-in I've found and I'd love to be able to use it again...
