### ISSUE TITLE
Adoption

### ISSUE THREAD

**Issue by lsellens** [lsellens/octoprint-manual_bed_tramming#30]
Do you mind if I just take this plugin over? It seems a lot of users are still using it myself included. I would like to rename it to something less misleading since nothing about it is specific to the cr10.

**Comment by electr0sheep** [comment]
I created an issue in the main plugin repo: https://github.com/OctoPrint/plugins.octoprint.org/issues/843

If you are still interested, can you leave a comment there? Thanks!

**Comment by lsellens** [comment]
If no one else is interested I will.
