### ISSUE TITLE
Despite bed settings are correct (200 x 200) Leveller RF and RB are just off the bed

### ISSUE THREAD

**Issue by bigalgeorge** [lsellens/octoprint-manual_bed_tramming#33]
I home using Octoprint home buttons, FrontRight and BackRight invalid as above, then did an Ender 3 Control Panel home, then this leveller, and same problem. Any ideas?
![2021-09-08_19-38](https://user-images.githubusercontent.com/6935387/132467515-8716cbd4-fb73-41d3-b7be-236af1f17c3b.png)

**Comment by lsellens** [comment]
if your printer is 200x200 why do you have your bed width set to 220x220?
