### ISSUE TITLE
"Apply Heat" shouldn't be your values

### ISSUE THREAD

**Issue by bcsteeve** [lsellens/octoprint-manual_bed_tramming#4]
They should be my values, not some random figure you thought would be nice.  It defaults to 50/170.  Why not *at least* go to what user has set for PLA?  Better... let them choose a profile

**Comment by nean-and-i** [comment]
this should be bed:80 and noozle:190, especially for leveling a higher bed temp is useful

**Comment by bcsteeve** [comment]
It shouldn't be any arbitrary value.  It should be user settable

**Comment by electr0sheep** [comment]
What would be the best way to implement the change? Text fields where users can enter their own values, or a drop down box where users can select an option from OctoPrint Settings>Temperatues>Presets?

**Comment by bcsteeve** [comment]
I suggest... if it is possible (I don't know) that you tap into the code that is already there where the user defined temperature/material profiles are, then show a dropdown.  Bed leveling is ideally performed with the same influencing factors as the printing.  So it should be the same temp the print job will use.

If it isn't worthwhile making it a UI element, then just give some details on how to edit the file and make the changes stick (you gave me a hint on the uninstall issue).  Perhaps I'm more precise than most and not enough people care? I'm ok with that.

**Comment by thisiskeithb** [comment]
Pulling from the system values for preheat settings would be nice, but I'm not sure what Octoprint exposes to plugins.

**Comment by electr0sheep** [comment]
What I'll probably end up doing for the first attempt is to have a number input for the values, and then I can try to populate a drop down based on the system values. I'm pretty sure those settings are exposed. I pretty much have all that done, but the controls aren't updated until the user refreshes the page, so that's what's going on with that.

**Comment by electr0sheep** [comment]
#9
