### ISSUE TITLE
"Home" button might be nice

### ISSUE THREAD

**Issue by electr0sheep** [lsellens/octoprint-manual_bed_tramming#8]
If the CR-10 is started with the z-axis out of line, the leveling buttons don't but the nozzle on the bed

**Comment by bcsteeve** [comment]
But... isn't there a home button directly above in the standard "controls"?  Why would we need a second one on the same page?

**Comment by electr0sheep** [comment]
@bcsteeve yep, you're absolutely correct. I totally forgot about the other controls lol.
