### ISSUE TITLE
basic extensibility

### ISSUE THREAD

**Issue by BETLOG** [lsellens/octoprint-manual_bed_tramming#9]
This would be MUCH more useful if the XY values could be user defined, and just call it a level assist plugin.

**Comment by govido** [comment]
Why not use this instead?
https://plugins.octoprint.org/plugins/touchtest/

**Comment by electr0sheep** [comment]
I have nearly finished work on this with the [customizable-controls branch](https://github.com/electr0sheep/OctoPrint-Cr10_leveling/tree/customizable-commands), but after saving the new settings, the user has to refresh the page for the changes to actually take effect. I think the solution might have something to do with the function rerenderControls() (I tried to find documentation for this function, but I couldn't)

**Comment by electr0sheep** [comment]
https://github.com/electr0sheep/OctoPrint-Cr10_leveling/issues/4

**Comment by electr0sheep** [comment]
#4

**Comment by electr0sheep** [comment]
#4

**Comment by BETLOG** [comment]
@govido Also good. But the point is that the bed parameters should either be read from the active octo profile, or user editable in the GUI.
Right now I'm using the 'custom control editor' to do exactly that. 
![selection_2018-02-28--14-33-55](https://user-images.githubusercontent.com/12265451/36770198-c3f344d2-1c94-11e8-9a0e-c9a3c5b989b0.png)

This (and the one you linked)  kind of 'convenience feature' plugin needs to have the same functionality, but in a no-brainer package that doesn't incorrectly assume it knows the bed size.

**Comment by electr0sheep** [comment]
I think at this point, I have added some basic extensibility features, therefore I'm going to close this issue.
